apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv1
    labels:
        name: pv1
spec:
    storageClassName: pv1class
    capacity: 
        storage: 1Gi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: "/root/pv1"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: pvc1
    labels:
        name: pvc1
spec:
    storageClassName: pv1class
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: hellodeploy
spec:
    replicas: 2
    selector:
        matchLabels:
            app: helloapp
    template:
        metadata: 
            labels: 
                app: helloapp
        spec:
            containers:
            - name: busybox-containers
              image: busybox
              ports:
              - containerPort: 80
              volumeMounts:
              - name: helloapp-storage
                mountPath: /var/www/html
            volumes:
            - name: helloapp-storage
              PersistentVolumeClaim: 
                claimName: pvc1