apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv1
    labels:
        name: pv1
spec:
    storageClassName: PV1Class
    capacity: 
        storage: 1Gi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: "/root/pv1"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: pvc1
    labels:
        name: pvc1
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
